# -*- coding: utf-8 -*-
"""PDF Reader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQ9-I7sjlI_OilvB1C_SR21SP7ISOc68
"""

from google.colab import files
uploaded = files.upload()

!pip install PyMuPDF

import fitz  # PyMuPDF

# Open the PDF file
pdf_file = 'Replace with the actual file name'  # Replace with the actual file name.

# Open the PDF document
pdf_document = fitz.open(pdf_file)

# Define a function to extract specific data
def extract_specific_lines(pdf_document, start_page, end_page, line_numbers):
    extracted_lines = []

    for page_num in range(start_page, end_page + 1):
        page = pdf_document[page_num]
        page_text = page.get_text()
        page_lines = page_text.split('\n')

        for line_number in line_numbers:
            if 0 <= line_number < len(page_lines):
                extracted_lines.append(page_lines[line_number])

    return extracted_lines

# Specify the range of pages and the line numbers you want to extract
start_page = 0  # Replace with the desired start page number
end_page = pdf_document.page_count - 1  # End page number
line_numbers = [2, 29]  # Replace with the desired line numbers

# Extract specific lines
extracted_lines = extract_specific_lines(pdf_document, start_page, end_page, line_numbers)

# Close the PDF document
pdf_document.close()


lines_extracted = []
# Print the extracted lines
for i, line_text in enumerate(extracted_lines):
    page_number = start_page + (i // len(line_numbers) if len(line_numbers) > 1 else 0)
    line_number = i % len(line_numbers)
    print(f"Page {page_number + 1}, Line {line_number + 1}: {line_text}")
    lines_extracted.append(line_text)

#print(lines_extracted)

!pip install pandas
import pandas as pd

df = pd.DataFrame({'ExtractedLines': lines_extracted})

output_excel_file = 'output_data.xlsx'  # Specify the desired output file name
df.to_excel(output_excel_file, index=False)  # Set index to False to exclude the index column in the Excel file